### ISSUE TITLE
External Data Sources

### ISSUE THREAD

**Issue by andrewMacmurray** [TechforgoodCAST/tech-for-good-near-you#10]
Need to decide which data sources we'd like to combine and how to do this

**Comment by andrewMacmurray** [comment]
@eghale we've had a look through the meetup groups and managed to pull some data in about the events in london, manchester and cambridge. Unfortunately there are only 4 upcoming events lol so we definitely need some different data sources to add to that 😆

**Comment by eghale** [comment]
OK here's a bigger list (all on Meetup so far but I'll keep adding to it): https://docs.google.com/spreadsheets/d/14ugF7_Vbad3FgZPs_fYhbW4EkVz_AK5NnsZ0TYXB_2o/edit#gid=0

Should be some more in there to keep you busy @andrewMacmurray! :)

**Comment by andrewMacmurray** [comment]
thanks @eghale will have a look through

**Comment by eghale** [comment]
@andrewMacmurray  Wonder if there's a way to scrape Twitter as well. Search terms I'd include would be "#techforgood", "#tech4good", "#impactech", "socinn" and "meetup"/"event"

Also you may want to look at this and see if there's a way of pulling these in as well (the UK ones): https://digitalsocial.eu/events

Strategically though, I think it might be better if we stick to grassroots community meetups rather than trying to pull in all the big conferences, as the site above is already trying to do that (not very effectively, but hey). Might help focus it a bit better too. What d'you reckon?

**Comment by andrewMacmurray** [comment]
closed as able to add custom events with admin dashboard #60
